//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN_THE_SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIEN_THE_SAN_PHAM()
        {
            this.TONKHO_SIZE = new HashSet<TONKHO_SIZE>();
        }
    
        public int ID { get; set; }
        public string MASANPHAM { get; set; }
        public string MAUSAC { get; set; }
        public decimal GIATHEOMAU { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONKHO_SIZE> TONKHO_SIZE { get; set; }
    }
}
