//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIASANPHAM
    {
        public string MADANHGIA { get; set; }
        public string MAKHACHHANG { get; set; }
        public string MASANPHAM { get; set; }
        public Nullable<int> DIEM { get; set; }
        public string BINHLUAN { get; set; }
        public Nullable<System.DateTime> NGAYDANHGIA { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
