//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
            this.DANHGIASANPHAM = new HashSet<DANHGIASANPHAM>();
        }
    
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public string MOTA { get; set; }
        public decimal GIA { get; set; }
        public Nullable<decimal> GIAKHUYENMAI { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string MANHACUNGCAP { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIASANPHAM> DANHGIASANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
