//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string MATAIKHOAN { get; set; }
        public string TENTAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string LOAITAIKHOAN { get; set; }
        public string MAKHACHHANG { get; set; }
        public string MANHANVIEN { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
