//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO_SIZE
    {
        public int ID { get; set; }
        public string MASANPHAM { get; set; }
        public int SIZE { get; set; }
        public int SOLUONG { get; set; }
        public Nullable<int> IDBienThe { get; set; }
    
        public virtual BIEN_THE_SAN_PHAM BIEN_THE_SAN_PHAM { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
