//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HoaDonDayDu
    {
        public string MAHOADON { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string TenKH { get; set; }
        public string TenNV { get; set; }
    }
}
