//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SanPham_NCC
    {
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public decimal GIA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string TENNHACUNGCAP { get; set; }
    }
}
