//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGIay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserCart
    {
        public string MAKHACHHANG { get; set; }
        public string MASANPHAM { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string TENSANPHAM { get; set; }
        public decimal unitPrice { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
    }
}
